language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r blog-spring-aws *
  - mkdir -p deploy
  - mv blog-spring-aws.zip deploy/blog-spring-aws.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo settiongs에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settiongs에 설정된 값
    bucket: blog-spring-aws-build # S3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip파일 접근을 private로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo settiongs에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settiongs에 설정된 값
    bucket: blog-spring-aws-build #S3버킷
    key: blog-spring-aws.zip #빌드 파일을 압축해서 전달
    bundle_type: zip #압축 확장자
    application: blog-spring-aws #웹 콘솔에서 등록한 codeDeploy 애플리케이션
    deployment_group: blog-spring-aws-group #웹 콘솔에서 등록한 codePloy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      -tingtangting9398@gmail.com